builder:
  track: dev

labels:
  team: estafette-tea

version:
  semver:
    major: 0
    minor: 0

stages:
  # build:
  #   image: golang:1.14.4-alpine3.12
  #   env:
  #     CGO_ENABLED: 0
  #     GOOS: linux
  #     API_BASE_URL: estafette.secret(AJwsqWlJSLjiUOPz.FTuJpmMFZLqJZOO7D56F0VhyeDDPH6YvdBdnO0ZSRx1iHawXycCSMfruacdwI4Txxq9wjHyGkxTK8td8.GiaJvmVdZfaDeri_Go-Qw1goeDqPFrw1cl9rIUZSGBBqXOUQzsiQPa-zecZQqD5Lr6iDZhVWZ6a09v79L2Ro40rn_-Qn)
  #     CLIENT_ID: estafette.secret(HMxwhjF7i2ZX5bDy.fPTrGeOKCs2Nigu4OhxIuBfNOXQdRiQ8cDJ6UsHQu03BDTgSPeReFZrczkL2BDeh_GLGnA==.KP-sRaffQs_PhhDofUUd6keMYCgARTRldGx5EtaAp0ucQm9Wa6l_qokp6POH0LRTEcIhVC0vOIInnZS6y0U9CvQrVeqq)
  #     CLIENT_SECRET: estafette.secret(cPTXmCkF995gknjX.bFsXQTs_WAJ-5s_Ve8zVNvQDMFYrOeU7gPm0xvn1Z8sZlwkTL3w96KWgmyAqIOlObS2_KUK8vLuMUqpfeek2SGs-Ujjh6cid43fZMBmc5nA=.ZmM0WyMaMyZwwKuHXvOCCfobJ2FmatMgmKmH0cCpAPsD9TwWH1N8zv62sSMvHNEWOwCzO0Z35S2WOjJ79MQt-Evr-TAb)
  #   commands:
  #   - cd src
  #   - go test ./...

  clone-web-repo:
    image: extensions/git-clone:dev
    repo: estafette-ci-web
    branch: master

  build-web:
    image: node:13.6.0-alpine
    commands:
    - cd estafette-ci-web
    - npm ci
    - npm run build
    - ls -latr ./dist
    - cp -r ./dist ../
    - cd ..
    - rm -rf estafette-ci-web
  
  trigger-github-pages-build:
    image: extensions/github-pages:dev
    token: estafette.secret(N-zMCcPQnKYI5Km4.P3AN60mmox8JRoUpFxCdWGsL8CAmvVJ_2inVz7TV4stWN_pdu4xb3TIvvRXyEYP0dFwEzIthYsQ=)
    when:
      status == 'succeeded' &&
      branch == 'master'